language: python

python:
  - "3.4"

env:
  - DJANGO_VERSION=1.4.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
  - pip install numpy
  - pip install scipy
  - pip install matplotlib

script: python rep1/fizzbuzz.py
